# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146Abpz9zQEiNjMShU7KqsGc3_thIqXPc
"""

import streamlit as st
import cv2
import numpy as np
import joblib
import os
import urllib.request
from PIL import Image
import gdown
from scipy.stats import skew
from skimage.feature import graycomatrix, graycoprops

# the function thet take data from google run itself
import os
import gdown
import os
import gdown
@st.cache_resource
def load_model():
    model_filename = 'plant_disease_model.joblib'
    
    if not os.path.exists(model_filename):
        with st.spinner("file is downloading... please wait..."):
            # enter your drive id
            file_id = "1JKsGhoUL6Zw49ZbG6k7Gdbbx8o_9GhoH" 
            download_url = f"https://drive.google.com/uc?id={file_id}"
            gdown.download(download_url, model_filename, quiet=False)
            
    return joblib.load(model_filename)

# run the model
try:
    model = load_model()
except Exception as e:
    st.error(f"can't find or download the file {e}. confirm firstly if the Google Drive ID is correct and sharing is set to public.")

def extract_features_from_image(pil_image):
    # convert PIL image to OpenCV (numpy array) format
    img = np.array(pil_image)
    # Streamlit give RGB image, OpenCV-requires BGR image
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    # resize the image to keep all inputs in same size (256x256)
    img = cv2.resize(img, (256, 256))

    # Leaf Segmentation (Otsu's Thresholding)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    _, mask = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # Color space conversion (HSV and Lab)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)

    leaf_pixels_hsv = hsv[mask == 255]
    leaf_pixels_lab = lab[mask == 255]

    if len(leaf_pixels_hsv) == 0:
        return None

    features = []

    # Color features (Color moments: Mean, Std, skew)
    channels = [
        leaf_pixels_hsv[:, 0], # H channel
        leaf_pixels_hsv[:, 1], # S channel
        leaf_pixels_lab[:, 1], # A channel
        leaf_pixels_lab[:, 2]  # B channel
    ]

    # for every channel measure Mean, Std, Skew
    for ch in channels:
        features.append(np.mean(ch))
        features.append(np.std(ch))
        features.append(skew(ch))

    # Texture features using GLCM
    glcm = graycomatrix(gray, distances=[1], angles=[0, np.pi/4, np.pi/2, 3*np.pi/4],
                        levels=256, symmetric=True, normed=True)

    features.append(np.mean(graycoprops(glcm, 'contrast')))
    features.append(np.mean(graycoprops(glcm, 'homogeneity')))
    features.append(np.mean(graycoprops(glcm, 'energy')))
    features.append(np.mean(graycoprops(glcm, 'correlation')))

    # to predict the image convert 2D (1-Row, 16-Columns)
    return np.array(features).reshape(1, -1)

# 3. Streamlit (User Interface)
st.set_page_config(
    page_title="PLANT DISEASE PREDICTOR", 
    page_icon="🌾",
    layout="centered"
)

# set(Background Image)
def add_bg_from_url():
    st.markdown(
         f"""
         <style>
         .stApp {{
             background-image: url("https://4kwallpapers.com/images/walls/thumbs_2t/8446.jpg");
             background-attachment: fixed;
             background-size: cover;
         }}
         /* set dark backround */
         .main .block-container {{
             background-color: rgba(0, 0, 0, 0.75);
             padding: 2.5rem;
             border-radius: 15px;
             color: #ffffff;
             box-shadow: 0px 4px 15px rgba(0, 0, 0, 0.5);
         }}
         h1, h2, h3, p, span {{
             color: #ffffff !important;
         }}
         </style>
         """,
         unsafe_allow_html=True
    )

# apply backround picture
add_bg_from_url()

# ----------------- SIDEBAR (SLIDE BAR) -----------------
st.sidebar.title("⚙️ Control Panel")
st.sidebar.write("Configure your prediction settings below:")

#select input method (Input Method)
input_option = st.sidebar.radio(
    "Choose Input Method:", 
    ("📁 Upload Image File", "📸 Take a Photo with Camera")
)

st.sidebar.markdown("---")

# (Leaf Prediction Tips)
st.sidebar.subheader("💡 Tips for Best Prediction")
st.sidebar.markdown("""
* **Good Lighting:**
* **Focus on Leaf:** 
* **Single Leaf:** 
""")

st.sidebar.markdown("---")
st.sidebar.info("Designed & Developed for Plant Health Monitoring.")

# ----------------- MAIN PAGE CONTENT -----------------
st.title("🌾 Disease Identifier Application")
st.write("Upload an image or use your camera in the sidebar to check if your plant is infected or healthy.")

# shou input option in slide bar
uploaded_file = None
if "Upload Image" in input_option:
    uploaded_file = st.file_uploader("Upload image of leaf ...", type=["jpg", "jpeg", "png"])
else:
    uploaded_file = st.camera_input("Take a picture of the plant leaf...")

# prediction and classification section
if uploaded_file is not None:
    # show the image
    image = Image.open(uploaded_file)
    st.image(image, caption='SELECTED IMAGE', use_container_width=True)

    # Predict Button
    if st.button("Test the Leaf"):
        with st.spinner("Extracting features and calculating... Please wait."):
            features = extract_features_from_image(image)

            if features is None:
                st.error("Can't identify the image. Please upload or take a clearer image of a leaf.")
            else:
                # testing
                prediction = model.predict(features)

                # classificaation part
                st.subheader("Predicted Decision:")
                if prediction[0] == 0:
                    st.success("🎉 **The Leaf is Healthy! (Healthy)**")
                    st.balloons() 
                else:
                    st.error("🚨 **The Leaf is Infected! (Infected)**")
